apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-ai-chatbot.fullname" . }}-secrets
  labels:
    {{- include "todo-ai-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  openrouter-api-key: {{ .Values.app.env.OPENROUTER_API_KEY | b64enc | quote }}
  better-auth-secret: {{ .Values.app.env.BETTER_AUTH_SECRET | b64enc | quote }}