"""
Agent executor for running structured plans with tool calls.
"""
import json
import logging
from typing import List, Dict, Any, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.api_contract import PlanStep
from app.mcp.tools.add_task import handle_add_task
from app.mcp.tools.list_tasks import handle_list_tasks
from app.mcp.tools.update_task import handle_update_task
from app.mcp.tools.delete_task import handle_delete_task
from app.mcp.tools.complete_task import handle_complete_task
from app.models.message import Message, MessageRole


logger = logging.getLogger(__name__)


class AgentExecutor:
    """Class to execute structured plans generated by the planner."""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def execute_plan(self, user_id: str, plan: List[PlanStep], conversation_id: Optional[int] = None) -> str:
        """
        Execute a structured plan with multiple steps.

        Args:
            user_id: User identifier
            plan: List of PlanStep objects to execute
            conversation_id: Optional conversation ID for logging tool calls

        Returns:
            Final response string after executing all steps
        """
        results = []

        for step in plan:
            try:
                # Update step status to executing
                step.status = "executing"

                # Execute the step based on its tool_name
                if step.tool_name:
                    result = await self.execute_tool_step(user_id, step, conversation_id)
                    results.append({
                        "step_id": step.id,
                        "description": step.description,
                        "tool_name": step.tool_name,
                        "arguments": step.arguments,
                        "result": result
                    })

                    # Log the tool call in the conversation if conversation_id is provided
                    if conversation_id:
                        await self.log_tool_call(conversation_id, user_id, step, result)
                else:
                    # For steps without tools, just record the description
                    results.append({
                        "step_id": step.id,
                        "description": step.description,
                        "result": step.description
                    })

                # Mark step as completed
                step.status = "completed"

            except Exception as e:
                logger.error(f"Error executing step {step.id}: {str(e)}")
                step.status = "failed"
                results.append({
                    "step_id": step.id,
                    "description": step.description,
                    "error": str(e)
                })

        # Generate final response based on execution results
        return self.generate_final_response(results)

    async def execute_tool_step(self, user_id: str, step: PlanStep, conversation_id: Optional[int] = None) -> Any:
        """
        Execute a single tool-based step.

        Args:
            user_id: User identifier
            step: PlanStep object with tool information
            conversation_id: Optional conversation ID for logging

        Returns:
            Result of the tool execution
        """
        tool_name = step.tool_name
        arguments = step.arguments or {}

        # Add user_id to arguments for MCP tools
        arguments['user_id'] = user_id

        try:
            if tool_name == "add_task":
                result = await handle_add_task(self.db, **arguments)
            elif tool_name == "list_tasks":
                result = await handle_list_tasks(self.db, **arguments)
            elif tool_name == "update_task":
                result = await handle_update_task(self.db, **arguments)
            elif tool_name == "delete_task":
                result = await handle_delete_task(self.db, **arguments)
            elif tool_name == "complete_task":
                result = await handle_complete_task(self.db, **arguments)
            else:
                raise ValueError(f"Unknown tool: {tool_name}")

            return result
        except Exception as e:
            logger.error(f"Error executing tool {tool_name}: {str(e)}")
            return {"error": f"Error executing {tool_name}: {str(e)}"}

    async def log_tool_call(self, conversation_id: int, user_id: str, step: PlanStep, result: Any):
        """
        Log the tool call in the conversation for history tracking.

        Args:
            conversation_id: Conversation ID to log the tool call
            user_id: User ID
            step: PlanStep that was executed
            result: Result of the tool execution
        """
        tool_message = Message(
            conversation_id=conversation_id,
            user_id=user_id,
            role=MessageRole.TOOL,
            content=json.dumps(result),
            tool_calls=json.dumps({
                "name": step.tool_name,
                "arguments": step.arguments
            })
        )
        self.db.add(tool_message)
        await self.db.commit()

    def generate_final_response(self, results: List[Dict[str, Any]]) -> str:
        """
        Generate a human-readable response from execution results.

        Args:
            results: List of execution results from each step

        Returns:
            Formatted response string
        """
        successful_steps = [r for r in results if "error" not in r]
        failed_steps = [r for r in results if "error" in r]

        response_parts = []

        if successful_steps:
            response_parts.append(f"I've completed {len(successful_steps)} steps:")
            for result in successful_steps:
                if "tool_name" in result:
                    response_parts.append(f"- {result['description']}: {json.dumps(result['result'])}")
                else:
                    response_parts.append(f"- {result['description']}")

        if failed_steps:
            response_parts.append(f"\n{len(failed_steps)} steps failed:")
            for result in failed_steps:
                response_parts.append(f"- {result['description']}: {result['error']}")

        return "\n".join(response_parts)